[package]
name = "add-reservation"
version = "0.1.0"
authors = ["Jacek Chmielewski <jchmielewski@teonite.com>"]
edition = "2021"

[[bin]]
name = "add_reservation"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = { path = "../../../contract" }
casper-types = { path = "../../../../types" }
