[package]
name = "vm2-cep18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
casper-macros = { path = "../../../macros" }
casper-sdk = { path = "../../../sdk" }
borsh = { version = "1.2.0", features = ["derive", "unstable__schema"] }
vm-common = { path = "../../../../vm-common" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
serde_json = "1"
ctor = "0.2.4"
casper-sdk = { path = "../../../sdk", features = ["cli"] }

[dev-dependencies]
casper-sdk-codegen = { path = "../../../sdk-codegen" }

[build-dependencies]
casper-sdk-codegen = { path = "../../../sdk-codegen" }
