[package]
name = "vm2-harness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
casper-macros = { path = "../../../macros" }
casper-sdk = { path = "../../../sdk" }
borsh = { version = "1.2.0", features = ["derive", "unstable__schema"] }
vm-common = {"path" = "../../../../vm-common"}
impls = "1"
thiserror = "1"
