[package]
name = "casper-sdk"
version = "0.1.0"
edition = "2021"
authors = ["Michał Papierski <michal@casperlabs.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "1.2.0"
bytes = "1"
vm-common = {path="../../vm-common"}
bitflags = "2.4.1"

# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ctor = "0.2.5"
