[package]
name = "casper-sdk"
version = "0.1.0"
edition = "2021"
authors = ["Michał Papierski <michal@casperlabs.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = { version = "1.2.0", features = ["derive"] }
bytes = "1"
vm-common = {path="../../vm-common"}
bitflags = "2.4.1"
const-fnv1a-hash = "1.1.0"
impl-trait-for-tuples = "0.2.2"
casper-sdk-sys = {path = "../sdk-sys" }

once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

clap = { version = "4", optional = true, features = ["derive"] }
thiserror = { version = "1", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand  = "0.8.5"
ctor = "0.2.7"
once_cell = "1.19.0"

[features]
default = []
cli = ["clap", "thiserror"]
